#+html: <a href="https://melpa.org/#/once"><img alt="MELPA" src="https://melpa.org/packages/once-badge.svg"/></a> <a href="https://stable.melpa.org/#/once"><img alt="MELPA Stable" src="https://stable.melpa.org/packages/once-badge.svg"/></a>
* once

This library provides two main functions:

- =once-hook=, substitute for =add-hook=
- =once-load=, substitute for =eval-after-load=

They are like =add-hook= and =eval-after-load= respectively, except that they only result in calling the provided function once: at the next time the hook is run or the file is loaded, respectively.

The variants

- =once-hook*=
- =once-load*=

can be explained if you think of the main functions as being called
"pushnew-self-deleting-hook", and these just "push-self-deleting-hook".

In other words, these variants are NOT idempotent; evaluating

#+begin_src elisp
(dotimes (_ 3)
  (once-hook* 'minibuffer-setup-hook #'my-func))
#+end_src

results in calling =my-func= three times at the next minibuffer setup.

The macros

- =once-hook!=
- =once-load!=

are meant to help with writing Emacs init-files.  See examples next section.

** Examples

Unset some default keys in =geiser-repl-mode-map=, when the file =geiser-repl.el= first loads:

    #+begin_src elisp
    (once-load! geiser-repl
      (keymap-unset geiser-repl-mode-map "M-," t)
      (keymap-unset geiser-repl-mode-map "M-." t)
      (keymap-unset geiser-repl-mode-map "M-`" t))
    #+end_src

Configure font after the Emacs daemon makes its first emacsclient frame:

    #+begin_src elisp
    (once-hook! server-after-make-frame-hook
      (set-face-font 'default (font-spec :family "Iosevka Nerd Font" :size 29)))
    #+end_src

** Examples with Llama

Setting hooks in init-files is a natural fit for the =##= macro from [[https://github.com/tarsius/llama][Llama]].
No problems combining that with this library:

    #+begin_src elisp
    (once-load 'org (##setopt org-todo-keywords '((sequence "IDEA" "DONE"))))
    #+end_src

Setting up a =my-first-frame-hook=, inspired by Doom Emacs's various doom-first-*-hook:

    #+begin_src elisp
    (defvar my-first-frame-hook nil)
    (if (daemonp)
        (once-hook 'server-after-make-frame-hook (##run-hooks 'my-first-frame-hook))
      (add-hook 'window-setup-hook (##run-hooks 'my-first-frame-hook)))
    #+end_src

The advantage of =once-hook= plus Llama, compared to =once-hook!=, is that
the former preserves the exact calling convention of =add-hook=.
That makes it trivial to rewrite from =add-hook= to =once-hook= and back.
No need to change any arguments nor quotations:

    #+begin_src elisp
    (add-hook  'enable-theme-functions (##message "Loaded theme %s" %) -50)
    (once-hook 'enable-theme-functions (##message "Loaded theme %s" %) -50)
    #+end_src


* Remarks

1. I've found =once-hook= to be surprisingly useful in general-purpose Elisp code.

   So this is not just for initfiles!

2. It will almost never matter that =once-load= only calls a thing once, because a given Elisp file rarely loads twice anyway.  But it feels safer and easier to reason about, in my opinion: a given invocation cannot ever result in more than one call of the given function.

   There are cases where you do want to load a file multiple times.  One such case is writing initfiles to be idempotent so that you can re-load them.  In that case, you'd like to be able to edit what goes in your `eval-after-load` expressions and avoid calling what you had put there earlier!

   The effect of =once-load= can also be undone.  The effect of =eval-after-load= is permanent and hard to undo.
